For compatibility with MS Visual Studio.
In the case of "1.0 / 0.0" compiler generates an error:
1>  kaldi-vector.cc
1>..\..\..\src\matrix\kaldi-vector.cc(523): error C2124: divide or mod by zero

If the constant 0.0 is replaced by a variable, then there is no error.