add -std=c++11 to solve make sctk error (#4355)
* add -std=c++11 to solve make sctk error

solve this problem:
make sctk, show error 
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support

* [tools] make sctk fix tar bug

mac:tools: tar --exclude '*NONE*html' -xmaf sctk-20159b5.tar.gz
tar: Option -a is not permitted in mode -x
make: *** [sctk] Error 1